export const mock = [
  {
    code: 2210271,
    event: 1,
    finished: true,
    finished_provisional: true,
    id: 1,
    kickoff_time: '2021-08-13T19:00:00Z',
    minutes: 90,
    provisional_start_time: false,
    started: true,
    team_a: 1,
    team_a_score: 0,
    team_h: 3,
    team_h_score: 2,
    stats: [
      { identifier: 'goals_scored', a: [], h: [Array] },
      { identifier: 'assists', a: [], h: [Array] },
      { identifier: 'own_goals', a: [], h: [] },
      { identifier: 'penalties_saved', a: [], h: [] },
      { identifier: 'penalties_missed', a: [], h: [] },
      { identifier: 'yellow_cards', a: [], h: [] },
      { identifier: 'red_cards', a: [], h: [] },
      { identifier: 'saves', a: [Array], h: [Array] },
      { identifier: 'bonus', a: [], h: [Array] },
      { identifier: 'bps', a: [Array], h: [Array] },
    ],
    team_h_difficulty: 3,
    team_a_difficulty: 2,
    pulse_id: 66342,
  },
]
